language: node_js
sudo: false

node_js:
  - "8"
  - "9"
  - "node"
  - "lts/*"

install:
  - npm install -g istanbul
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov